window.challenges = {
    "https://leetcode.com/problems/contains-duplicate/": {"text": "Contains Duplicate", "type": "Arrays & Hashing"},
    "https://leetcode.com/problems/valid-anagram/": {"text": "Valid Anagram", "type": "Arrays & Hashing"},
    "https://leetcode.com/problems/two-sum/": {"text": "Two Sum", "type": "Arrays & Hashing"},
    "https://leetcode.com/problems/group-anagrams/": {"text": "Group Anagrams", "type": "Arrays & Hashing"},
    "https://leetcode.com/problems/top-k-frequent-elements/": {"text": "Top K Frequent Elements", "type": "Arrays & Hashing"},
    "https://leetcode.com/problems/product-of-array-except-self/": {"text": "Product of Array Except Self", "type": "Arrays & Hashing"},
    "https://leetcode.com/problems/valid-sudoku/": {"text": "Valid Sudoku", "type": "Arrays & Hashing"},
    "https://leetcode.com/problems/encode-and-decode-strings/": {"text": "Encode and Decode Strings ", "type": "Arrays & Hashing"},
    "https://leetcode.com/problems/longest-consecutive-sequence/": {"text": "Longest Consecutive Sequence", "type": "Arrays & Hashing"},
    "https://leetcode.com/problems/valid-palindrome/": {"text": "Valid Palindrome", "type": "Two Pointers"},
    "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/": {"text": "Two Sum II Input Array Is Sorted", "type": "Two Pointers"},
    "https://leetcode.com/problems/3sum/": {"text": "3Sum", "type": "Two Pointers"},
    "https://leetcode.com/problems/container-with-most-water/": {"text": "Container With Most Water", "type": "Two Pointers"},
    "https://leetcode.com/problems/trapping-rain-water/": {"text": "Trapping Rain Water", "type": "Two Pointers"},
    "https://leetcode.com/problems/valid-parentheses/": {"text": "Valid Parentheses", "type": "Stack"},
    "https://leetcode.com/problems/min-stack/": {"text": "Min Stack", "type": "Stack"},
    "https://leetcode.com/problems/evaluate-reverse-polish-notation/": {"text": "Evaluate Reverse Polish Notation", "type": "Stack"},
    "https://leetcode.com/problems/generate-parentheses/": {"text": "Generate Parentheses", "type": "Stack"},
    "https://leetcode.com/problems/daily-temperatures/": {"text": "Daily Temperatures", "type": "Stack"},
    "https://leetcode.com/problems/car-fleet/": {"text": "Car Fleet", "type": "Stack"},
    "https://leetcode.com/problems/largest-rectangle-in-histogram/": {"text": "Largest Rectangle In Histogram", "type": "Stack"},
    "https://leetcode.com/problems/binary-search/": {"text": "Binary Search", "type": "Binary Search"},
    "https://leetcode.com/problems/search-a-2d-matrix/": {"text": "Search a 2D Matrix", "type": "Binary Search"},
    "https://leetcode.com/problems/koko-eating-bananas/": {"text": "Koko Eating Bananas", "type": "Binary Search"},
    "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/": {"text": "Find Minimum In Rotated Sorted Array", "type": "Binary Search"},
    "https://leetcode.com/problems/search-in-rotated-sorted-array/": {"text": "Search In Rotated Sorted Array", "type": "Binary Search"},
    "https://leetcode.com/problems/time-based-key-value-store/": {"text": "Time Based Key Value Store", "type": "Binary Search"},
    "https://leetcode.com/problems/median-of-two-sorted-arrays/": {"text": "Median of Two Sorted Arrays", "type": "Binary Search"},
    "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/": {"text": "Best Time to Buy And Sell Stock", "type": "Sliding Window"},
    "https://leetcode.com/problems/longest-substring-without-repeating-characters/": {"text": "Longest Substring Without Repeating Characters", "type": "Sliding Window"},
    "https://leetcode.com/problems/longest-repeating-character-replacement/": {"text": "Longest Repeating Character Replacement", "type": "Sliding Window"},
    "https://leetcode.com/problems/permutation-in-string/": {"text": "Permutation In String", "type": "Sliding Window"},
    "https://leetcode.com/problems/minimum-window-substring/": {"text": "Minimum Window Substring", "type": "Sliding Window"},
    "https://leetcode.com/problems/sliding-window-maximum/": {"text": "Sliding Window Maximum", "type": "Sliding Window"},
    "https://leetcode.com/problems/reverse-linked-list/": {"text": "Reverse Linked List", "type": "Linked List"},
    "https://leetcode.com/problems/merge-two-sorted-lists/": {"text": "Merge Two Sorted Lists", "type": "Linked List"},
    "https://leetcode.com/problems/reorder-list/": {"text": "Reorder List", "type": "Linked List"},
    "https://leetcode.com/problems/remove-nth-node-from-end-of-list/": {"text": "Remove Nth Node From End of List", "type": "Linked List"},
    "https://leetcode.com/problems/copy-list-with-random-pointer/": {"text": "Copy List With Random Pointer", "type": "Linked List"},
    "https://leetcode.com/problems/add-two-numbers/": {"text": "Add Two Numbers", "type": "Linked List"},
    "https://leetcode.com/problems/linked-list-cycle/": {"text": "Linked List Cycle", "type": "Linked List"},
    "https://leetcode.com/problems/find-the-duplicate-number/": {"text": "Find The Duplicate Number", "type": "Linked List"},
    "https://leetcode.com/problems/lru-cache/": {"text": "LRU Cache", "type": "Linked List"},
    "https://leetcode.com/problems/merge-k-sorted-lists/": {"text": "Merge K Sorted Lists", "type": "Linked List"},
    "https://leetcode.com/problems/reverse-nodes-in-k-group/": {"text": "Reverse Nodes In K Group", "type": "Linked List"},
    "https://leetcode.com/problems/invert-binary-tree/": {"text": "Invert Binary Tree", "type": "Trees"},
    "https://leetcode.com/problems/maximum-depth-of-binary-tree/": {"text": "Maximum Depth of Binary Tree", "type": "Trees"},
    "https://leetcode.com/problems/diameter-of-binary-tree/": {"text": "Diameter of Binary Tree", "type": "Trees"},
    "https://leetcode.com/problems/balanced-binary-tree/": {"text": "Balanced Binary Tree", "type": "Trees"},
    "https://leetcode.com/problems/same-tree/": {"text": "Same Tree", "type": "Trees"},
    "https://leetcode.com/problems/subtree-of-another-tree/": {"text": "Subtree of Another Tree", "type": "Trees"},
    "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/": {"text": "Lowest Common Ancestor of a Binary Search Tree", "type": "Trees"},
    "https://leetcode.com/problems/binary-tree-level-order-traversal/": {"text": "Binary Tree Level Order Traversal", "type": "Trees"},
    "https://leetcode.com/problems/binary-tree-right-side-view/": {"text": "Binary Tree Right Side View", "type": "Trees"},
    "https://leetcode.com/problems/count-good-nodes-in-binary-tree/": {"text": "Count Good Nodes In Binary Tree", "type": "Trees"},
    "https://leetcode.com/problems/validate-binary-search-tree/": {"text": "Validate Binary Search Tree", "type": "Trees"},
    "https://leetcode.com/problems/kth-smallest-element-in-a-bst/": {"text": "Kth Smallest Element In a Bst", "type": "Trees"},
    "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal": {"text": "Construct Binary Tree From Preorder And Inorder Traversal", "type": "Trees"},
    "https://leetcode.com/problems/binary-tree-maximum-path-sum/": {"text": "Binary Tree Maximum Path Sum", "type": "Trees"},
    "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/": {"text": "Serialize And Deserialize Binary Tree", "type": "Trees"},
    "https://leetcode.com/problems/implement-trie-prefix-tree/": {"text": "Implement Trie Prefix Tree", "type": "Tries"},
    "https://leetcode.com/problems/design-add-and-search-words-data-structure/": {"text": "Design Add And Search Words Data Structure", "type": "Tries"},
    "https://leetcode.com/problems/word-search-ii/": {"text": "Word Search II", "type": "Tries"},
    "https://leetcode.com/problems/subsets/": {"text": "Subsets", "type": "Backtracking"},
    "https://leetcode.com/problems/combination-sum/": {"text": "Combination Sum", "type": "Backtracking"},
    "https://leetcode.com/problems/permutations/": {"text": "Permutations", "type": "Backtracking"},
    "https://leetcode.com/problems/subsets-ii/": {"text": "Subsets II", "type": "Backtracking"},
    "https://leetcode.com/problems/combination-sum-ii/": {"text": "Combination Sum II", "type": "Backtracking"},
    "https://leetcode.com/problems/word-search/": {"text": "Word Search", "type": "Backtracking"},
    "https://leetcode.com/problems/palindrome-partitioning/": {"text": "Palindrome Partitioning", "type": "Backtracking"},
    "https://leetcode.com/problems/letter-combinations-of-a-phone-number/": {"text": "Letter Combinations of a Phone Number", "type": "Backtracking"},
    "https://leetcode.com/problems/n-queens/": {"text": "N Queens", "type": "Backtracking"},
    "https://leetcode.com/problems/kth-largest-element-in-a-stream/": {"text": "Kth Largest Element In a Stream", "type": "Heap / Priority Queue"},
    "https://leetcode.com/problems/last-stone-weight/": {"text": "Last Stone Weight", "type": "Heap / Priority Queue"},
    "https://leetcode.com/problems/k-closest-points-to-origin/": {"text": "K Closest Points to Origin", "type": "Heap / Priority Queue"},
    "https://leetcode.com/problems/kth-largest-element-in-an-array/": {"text": "Kth Largest Element In An Array", "type": "Heap / Priority Queue"},
    "https://leetcode.com/problems/task-scheduler/": {"text": "Task Scheduler", "type": "Heap / Priority Queue"},
    "https://leetcode.com/problems/design-twitter/": {"text": "Design Twitter", "type": "Heap / Priority Queue"},
    "https://leetcode.com/problems/find-median-from-data-stream/": {"text": "Find Median From Data Stream", "type": "Heap / Priority Queue"},
    "https://leetcode.com/problems/number-of-islands/": {"text": "Number of Islands", "type": "Graphs"},
    "https://leetcode.com/problems/clone-graph/": {"text": "Clone Graph", "type": "Graphs"},
    "https://leetcode.com/problems/max-area-of-island/": {"text": "Max Area of Island", "type": "Graphs"},
    "https://leetcode.com/problems/pacific-atlantic-water-flow/": {"text": "Pacific Atlantic Water Flow", "type": "Graphs"},
    "https://leetcode.com/problems/surrounded-regions/": {"text": "Surrounded Regions", "type": "Graphs"},
    "https://leetcode.com/problems/rotting-oranges/": {"text": "Rotting Oranges", "type": "Graphs"},
    "https://leetcode.com/problems/walls-and-gates/": {"text": "Walls And Gates ", "type": "Graphs"},
    "https://leetcode.com/problems/course-schedule/": {"text": "Course Schedule", "type": "Graphs"},
    "https://leetcode.com/problems/course-schedule-ii/": {"text": "Course Schedule II", "type": "Graphs"},
    "https://leetcode.com/problems/redundant-connection/": {"text": "Redundant Connection", "type": "Graphs"},
    "https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph": {"text": "Number of Connected Components In An Undirected Graph ", "type": "Graphs"},
    "https://leetcode.com/problems/graph-valid-tree/": {"text": "Graph Valid Tree ", "type": "Graphs"},
    "https://leetcode.com/problems/word-ladder/": {"text": "Word Ladder", "type": "Graphs"},
    "https://leetcode.com/problems/climbing-stairs/": {"text": "Climbing Stairs", "type": "1-D Dynamic Programming"},
    "https://leetcode.com/problems/min-cost-climbing-stairs/": {"text": "Min Cost Climbing Stairs", "type": "1-D Dynamic Programming"},
    "https://leetcode.com/problems/house-robber/": {"text": "House Robber", "type": "1-D Dynamic Programming"},
    "https://leetcode.com/problems/house-robber-ii/": {"text": "House Robber II", "type": "1-D Dynamic Programming"},
    "https://leetcode.com/problems/longest-palindromic-substring/": {"text": "Longest Palindromic Substring", "type": "1-D Dynamic Programming"},
    "https://leetcode.com/problems/palindromic-substrings/": {"text": "Palindromic Substrings", "type": "1-D Dynamic Programming"},
    "https://leetcode.com/problems/decode-ways/": {"text": "Decode Ways", "type": "1-D Dynamic Programming"},
    "https://leetcode.com/problems/coin-change/": {"text": "Coin Change", "type": "1-D Dynamic Programming"},
    "https://leetcode.com/problems/maximum-product-subarray/": {"text": "Maximum Product Subarray", "type": "1-D Dynamic Programming"},
    "https://leetcode.com/problems/word-break/": {"text": "Word Break", "type": "1-D Dynamic Programming"},
    "https://leetcode.com/problems/longest-increasing-subsequence/": {"text": "Longest Increasing Subsequence", "type": "1-D Dynamic Programming"},
    "https://leetcode.com/problems/partition-equal-subset-sum/": {"text": "Partition Equal Subset Sum", "type": "1-D Dynamic Programming"},
    "https://leetcode.com/problems/insert-interval/": {"text": "Insert Interval", "type": "Intervals"},
    "https://leetcode.com/problems/merge-intervals/": {"text": "Merge Intervals", "type": "Intervals"},
    "https://leetcode.com/problems/non-overlapping-intervals/": {"text": "Non Overlapping Intervals", "type": "Intervals"},
    "https://leetcode.com/problems/meeting-rooms/": {"text": "Meeting Rooms ", "type": "Intervals"},
    "https://leetcode.com/problems/meeting-rooms-ii/": {"text": "Meeting Rooms II ", "type": "Intervals"},
    "https://leetcode.com/problems/minimum-interval-to-include-each-query/": {"text": "Minimum Interval to Include Each Query", "type": "Intervals"},
    "https://leetcode.com/problems/maximum-subarray/": {"text": "Maximum Subarray", "type": "Greedy"},
    "https://leetcode.com/problems/jump-game/": {"text": "Jump Game", "type": "Greedy"},
    "https://leetcode.com/problems/jump-game-ii/": {"text": "Jump Game II", "type": "Greedy"},
    "https://leetcode.com/problems/gas-station/": {"text": "Gas Station", "type": "Greedy"},
    "https://leetcode.com/problems/hand-of-straights/": {"text": "Hand of Straights", "type": "Greedy"},
    "https://leetcode.com/problems/merge-triplets-to-form-target-triplet/": {"text": "Merge Triplets to Form Target Triplet", "type": "Greedy"},
    "https://leetcode.com/problems/partition-labels/": {"text": "Partition Labels", "type": "Greedy"},
    "https://leetcode.com/problems/valid-parenthesis-string/": {"text": "Valid Parenthesis String", "type": "Greedy"},
    "https://leetcode.com/problems/reconstruct-itinerary/": {"text": "Reconstruct Itinerary", "type": "Advanced Graphs"},
    "https://leetcode.com/problems/min-cost-to-connect-all-points/": {"text": "Min Cost to Connect All Points", "type": "Advanced Graphs"},
    "https://leetcode.com/problems/network-delay-time/": {"text": "Network Delay Time", "type": "Advanced Graphs"},
    "https://leetcode.com/problems/swim-in-rising-water/": {"text": "Swim In Rising Water", "type": "Advanced Graphs"},
    "https://leetcode.com/problems/alien-dictionary/": {"text": "Alien Dictionary ", "type": "Advanced Graphs"},
    "https://leetcode.com/problems/cheapest-flights-within-k-stops/": {"text": "Cheapest Flights Within K Stops", "type": "Advanced Graphs"},
    "https://leetcode.com/problems/unique-paths/": {"text": "Unique Paths", "type": "2-D Dynamic Programming"},
    "https://leetcode.com/problems/longest-common-subsequence/": {"text": "Longest Common Subsequence", "type": "2-D Dynamic Programming"},
    "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/": {"text": "Best Time to Buy And Sell Stock With Cooldown", "type": "2-D Dynamic Programming"},
    "https://leetcode.com/problems/coin-change-ii/": {"text": "Coin Change II", "type": "2-D Dynamic Programming"},
    "https://leetcode.com/problems/target-sum/": {"text": "Target Sum", "type": "2-D Dynamic Programming"},
    "https://leetcode.com/problems/interleaving-string/": {"text": "Interleaving String", "type": "2-D Dynamic Programming"},
    "https://leetcode.com/problems/longest-increasing-path-in-a-matrix/": {"text": "Longest Increasing Path In a Matrix", "type": "2-D Dynamic Programming"},
    "https://leetcode.com/problems/distinct-subsequences/": {"text": "Distinct Subsequences", "type": "2-D Dynamic Programming"},
    "https://leetcode.com/problems/edit-distance/": {"text": "Edit Distance", "type": "2-D Dynamic Programming"},
    "https://leetcode.com/problems/burst-balloons/": {"text": "Burst Balloons", "type": "2-D Dynamic Programming"},
    "https://leetcode.com/problems/regular-expression-matching/": {"text": "Regular Expression Matching", "type": "2-D Dynamic Programming"},
    "https://leetcode.com/problems/single-number/": {"text": "Single Number", "type": "Bit Manipulation"},
    "https://leetcode.com/problems/number-of-1-bits/": {"text": "Number of 1 Bits", "type": "Bit Manipulation"},
    "https://leetcode.com/problems/counting-bits/": {"text": "Counting Bits", "type": "Bit Manipulation"},
    "https://leetcode.com/problems/reverse-bits/": {"text": "Reverse Bits", "type": "Bit Manipulation"},
    "https://leetcode.com/problems/missing-number/": {"text": "Missing Number", "type": "Bit Manipulation"},
    "https://leetcode.com/problems/sum-of-two-integers/": {"text": "Sum of Two Integers", "type": "Bit Manipulation"},
    "https://leetcode.com/problems/reverse-integer/": {"text": "Reverse Integer", "type": "Bit Manipulation"},
    "https://leetcode.com/problems/rotate-image/": {"text": "Rotate Image", "type": "Math & Geometry"},
    "https://leetcode.com/problems/spiral-matrix/": {"text": "Spiral Matrix", "type": "Math & Geometry"},
    "https://leetcode.com/problems/set-matrix-zeroes/": {"text": "Set Matrix Zeroes", "type": "Math & Geometry"},
    "https://leetcode.com/problems/happy-number/": {"text": "Happy Number", "type": "Math & Geometry"},
    "https://leetcode.com/problems/plus-one/": {"text": "Plus One", "type": "Math & Geometry"},
    "https://leetcode.com/problems/powx-n/": {"text": "Pow(x, n)", "type": "Math & Geometry"},
    "https://leetcode.com/problems/multiply-strings/": {"text": "Multiply Strings", "type": "Math & Geometry"},
    "https://leetcode.com/problems/detect-squares/": {"text": "Detect Squares", "type": "Math & Geometry"},
}

blind = ['https://leetcode.com/problems/contains-duplicate/', 'https://leetcode.com/problems/valid-anagram/', 'https://leetcode.com/problems/two-sum/', 'https://leetcode.com/problems/group-anagrams/', 'https://leetcode.com/problems/top-k-frequent-elements/', 'https://leetcode.com/problems/product-of-array-except-self/', 'https://leetcode.com/problems/encode-and-decode-strings/', 'https://www.lintcode.com/problem/659/', 'https://leetcode.com/problems/longest-consecutive-sequence/', 'https://leetcode.com/problems/valid-palindrome/', 'https://leetcode.com/problems/3sum/', 'https://leetcode.com/problems/container-with-most-water/', 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/', 'https://leetcode.com/problems/longest-substring-without-repeating-characters/', 'https://leetcode.com/problems/longest-repeating-character-replacement/', 'https://leetcode.com/problems/minimum-window-substring/', 'https://leetcode.com/problems/valid-parentheses/', 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/', 'https://leetcode.com/problems/search-in-rotated-sorted-array/', 'https://leetcode.com/problems/reverse-linked-list/', 'https://leetcode.com/problems/merge-two-sorted-lists/', 'https://leetcode.com/problems/reorder-list/', 'https://leetcode.com/problems/remove-nth-node-from-end-of-list/', 'https://leetcode.com/problems/linked-list-cycle/', 'https://leetcode.com/problems/merge-k-sorted-lists/', 'https://leetcode.com/problems/invert-binary-tree/', 'https://leetcode.com/problems/maximum-depth-of-binary-tree/', 'https://leetcode.com/problems/same-tree/', 'https://leetcode.com/problems/subtree-of-another-tree/', 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/', 'https://leetcode.com/problems/binary-tree-level-order-traversal/', 'https://leetcode.com/problems/validate-binary-search-tree/', 'https://leetcode.com/problems/kth-smallest-element-in-a-bst/', 'https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/', 'https://leetcode.com/problems/binary-tree-maximum-path-sum/', 'https://leetcode.com/problems/serialize-and-deserialize-binary-tree/', 'https://leetcode.com/problems/implement-trie-prefix-tree/', 'https://leetcode.com/problems/design-add-and-search-words-data-structure/', 'https://leetcode.com/problems/word-search-ii/', 'https://leetcode.com/problems/find-median-from-data-stream/', 'https://leetcode.com/problems/combination-sum/', 'https://leetcode.com/problems/word-search/', 'https://leetcode.com/problems/number-of-islands/', 'https://leetcode.com/problems/clone-graph/', 'https://leetcode.com/problems/pacific-atlantic-water-flow/', 'https://leetcode.com/problems/course-schedule/', 'https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/', 'https://www.lintcode.com/problem/3651/', 'https://leetcode.com/problems/graph-valid-tree/', 'https://www.lintcode.com/problem/178/', 'https://leetcode.com/problems/alien-dictionary/', 'https://www.lintcode.com/problem/892/', 'https://leetcode.com/problems/climbing-stairs/', 'https://leetcode.com/problems/house-robber/', 'https://leetcode.com/problems/house-robber-ii/', 'https://leetcode.com/problems/longest-palindromic-substring/', 'https://leetcode.com/problems/palindromic-substrings/', 'https://leetcode.com/problems/decode-ways/', 'https://leetcode.com/problems/coin-change/', 'https://leetcode.com/problems/maximum-product-subarray/', 'https://leetcode.com/problems/word-break/', 'https://leetcode.com/problems/longest-increasing-subsequence/', 'https://leetcode.com/problems/unique-paths/', 'https://leetcode.com/problems/longest-common-subsequence/', 'https://leetcode.com/problems/maximum-subarray/', 'https://leetcode.com/problems/jump-game/', 'https://leetcode.com/problems/insert-interval/', 'https://leetcode.com/problems/merge-intervals/', 'https://leetcode.com/problems/non-overlapping-intervals/', 'https://leetcode.com/problems/meeting-rooms/', 'https://www.lintcode.com/problem/920/', 'https://leetcode.com/problems/meeting-rooms-ii/', 'https://www.lintcode.com/problem/919/', 'https://leetcode.com/problems/rotate-image/', 'https://leetcode.com/problems/spiral-matrix/', 'https://leetcode.com/problems/set-matrix-zeroes/', 'https://leetcode.com/problems/number-of-1-bits/', 'https://leetcode.com/problems/counting-bits/', 'https://leetcode.com/problems/reverse-bits/', 'https://leetcode.com/problems/missing-number/', 'https://leetcode.com/problems/sum-of-two-integers/']
window.blind75 = {}
blind.forEach((href) => window.blind75[href] = true)